version: "2.4"

services:
  dotnetapp:
    build:
      context: ./
      dockerfile: "./SpiixBot/SpiixBot/Dockerfile"
    environment:
      LAVALINK_HOSTNAME: "lavalink" # don't change unless you know what you are doing
      PREFIX: "!"
      DISCORD_BOT_TOKEN: ""
      SPOTIFY_CLIENT_ID: ""
      SPOTIFY_SECRET: ""
      YOUTUBE_API_KEY: ""
    depends_on: 
      - lavalink
    links: 
      - lavalink
    volumes: 
      - ./SpiixBot:/SpiixBot
    restart: unless-stopped

  lavalink:
    build: ./Lavalink
    restart: unless-stopped